### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by vkatsuba**
Purpose of changes:
* Remove Travis
* Add GItHub Actions
* Provide correct specs for Dialyzer
* Fix eUnit

### CODE REVIEW

**Comment by vkatsuba** [comment]
[CI Result](https://github.com/vkatsuba/erlcron/actions/runs/3292145976)

**Comment by Santiniis** [comment]
Alright, everything seems cool to me, just going to give it up till thursday to see if anybody wants to give an opinion regarding the changes other than me, and if there isn't any, I'll proceed to merge them. Thank you for your contribution.

**Comment by Santiniis** [comment]
Aight, everything's fine for me, except one thing:
- While I understand that the context of the PR is to have GH Actions up, a single commit containing also the changes in code (completely different context) can be contained into the PR. Just not in the same commit.
  - I would ask you then to make atomic commits, instead of squashing everything. But I'll accept this for now. 
Thank you very much for your contribution!

**Comment by vkatsuba** [comment]
> Aight, everything's fine for me, except one thing:
> 
>     * While I understand that the context of the PR is to have GH Actions up, a single commit containing also the changes in code (completely different context) can be contained into the PR. Just not in the same commit.
>       
>       * I would ask you then to make atomic commits, instead of squashing everything. But I'll accept this for now.
>         Thank you very much for your contribution!

Clear. Will be done for future changes. Thanks!

**Pull request merged**
