### PR TITLE
OTP 18 compatability

### PR DESCRIPTION
**Pull request by cjkjellander**
erlcron can't be compiled with OTP 18 since deprecated have warnings and 'record(foo)' isn't valid syntax anymore.

This fixes compilation for OTP 18 and should work with older releases as well.

### CODE REVIEW

**Comment by ericbmerritt** [comment]
@cjkjellander I just merged another pull request with exactly the same fix. Nice commit hygiene btw.

**Comment by drobakowski** [comment]
@ericbmerritt correct me if I'm wrong, but the other PR #32 isn't compatible with older systems prior to 18.0 and will therefore fail in runtime on those systems right?

E.g. on 17.5:
```
1> erlang:timestamp().
** exception error: undefined function erlang:timestamp/0
```
I'm just curious because I've seen some older versions in the `.travis.yml` file. Maybe an introduction of a conditional compiler directive would solve this problem, if support for older systems is even wanted?

**Comment by solvip** [comment]
Yes, this breaks everything previous to 18.0.

**Comment by ericbmerritt** [comment]
@cjkjellander Thats a good catch. Let me revert the other pr. I would as that you remove the TODO comment. I tend not to like them in code and I don't think it buys us a lot here. I will merge this when thats done.

**Pull request closed without merging**
