### PR TITLE
Added workaround for erlang native receive timeout limit.

### PR DESCRIPTION
**Pull request by maximvl**
Hi, I made a workaround for timeout limit, it will use maximum timeout value while time to event exceeds it. In current version agent falls with timeout_value error.

### CODE REVIEW

**Comment by ericbmerritt** [comment]
@maximvl what problem are you trying to solve here?

**Comment by maximvl** [comment]
@ericbmerritt fail on scheduling tasks to very distant time in future, like several months.

**Comment by ericbmerritt** [comment]
I needed to dig in on this further but I suspect that it would be better to
support an 'infinity' atom or something along those lines, rather than an
arbitrarily high timeout value.

**Comment by maximvl** [comment]
I don't understand your idea about 'infinity' atom. Like in original unix cron you can setup timers on 5 minutes or 5 months or years, here in erlang we just have artificial internal limit with ~2 months, which I tried to workaround.

**Pull request closed without merging**
